source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BXForm_Example', :exclusive => true do
  pod "BXForm", :path => "../"
end

target 'BXForm_Tests', :exclusive => true do
  pod "BXForm", :path => "../"

  
end
